[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production", DATABASE_URL = "${{DATABASE_URL}}", FRONTEND_URL = "${{FRONTEND_URL}}", GITHUB_CLIENT_ID = "${{GITHUB_CLIENT_ID}}", GITHUB_CLIENT_SECRET = "${{GITHUB_CLIENT_SECRET}}", SESSION_SECRET = "${{SESSION_SECRET}}" }
