[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.production.services.backend]
tcpProxies = [{ applicationPort = 5000, externalPort = 443 }]
domains = ["${{RAILWAY_STATIC_URL}}"]

# Database service configuration
[[environments.production.services]]
serviceName = "postgres"